SELECT
    vehicle_cicles."Object" AS "Vehicle"
    , vehicle_cicles."Cycle Date"
    , vehicle_cicles."Organization"
    , vehicle_cicles."Start Time"
    , vehicle_cicles."End Time"
    , vehicle_cicles."Time Travel Empty" AS "Empty Travel Time"
    , vehicle_cicles."Stopped Empty Time" AS "Empty Stopped Time"
    , vehicle_cicles."Load Time"
    , vehicle_cicles."Stopped Loaded Time"
    , vehicle_cicles."Operating Hours"
    , vehicle_cicles."Kilometers Loaded"
    , vehicle_cicles."Kilometers Empty"
    , vehicle_cicles."Payload"
    , vehicle_cicles."Operator"
    , vehicle_cicles."Loading Point"
    , vehicle_cicles."Dumping Point"
    , vehicle_cicles."Haul Distance"
    , vehicle_cicles."Fuel Used"
    , vehicle_cicles."LoaderPasses" AS "Loader Passes"
FROM vehicle_cicles